# -*- coding: utf-8 -*-
"""A compressive study of Mental Health Trends Over Time Using Online Posts and Smart Recommendations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-7Ptei7SfnVsSpa-PYrRa7z2fSntDnq

# **A compressive study of Mental Health Trends Over Time Using Online Posts and Smart Recommendations**

## **AI-Based Mental Health Clustering**

This code automatically groups mental-health-related tweets into categories like stress, anxiety, depression, or neutral by converting text into vector embeddings and applying clustering. It first loads and cleans the dataset, merges all important text fields into one column, and generates sentence embeddings using a fast transformer model. Then it uses K-Means clustering to separate tweets into four groups without needing labels. Finally, it auto-assigns cluster names using keyword matching and saves the results.

Important Points

- Data Loading & Cleaning: Reads the CSV file, removes duplicates, fills missing values.

- Text Merging: Combines tweet, username, name, and place into a single “text” column.

- Embedding Generation: Uses all-MiniLM-L6-v2 model to convert text into numerical vectors.

- Unsupervised Clustering: Applies K-Means to form four mental-health clusters.

- Cluster Naming: Automatically assigns cluster labels (stress, anxiety, depression, neutral) using keyword matching.

- Saving Output: Exports the final predictions back into the CSV file.
"""

!pip install sentence-transformers -q

import pandas as pd
from sklearn.cluster import KMeans
from sentence_transformers import SentenceTransformer
import numpy as np

# ---------------------------------------------------
# 1️. LOAD DATA
# ---------------------------------------------------
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset.csv")   # <-- your uploaded file
df = df.fillna("")
df = df.drop_duplicates()

print("Data Loaded:", df.shape)

# ---------------------------------------------------
# 2️. MERGE TEXT COLUMNS
# ---------------------------------------------------
text_cols = ["tweet", "username", "name", "place"]

df["text"] = df[text_cols].agg(" ".join, axis=1).str.strip()

# ---------------------------------------------------
# 3️. EMBEDDING MODEL (VERY FAST)
# ---------------------------------------------------
model = SentenceTransformer("all-MiniLM-L6-v2")  # GPU-supported, super fast

print("Encoding Text...")
emb = model.encode(df["text"].tolist(), batch_size=32, show_progress_bar=True)

# ---------------------------------------------------
# 4️. CLUSTERING (Unsupervised Mental Health Topics)
# ---------------------------------------------------
k = 4  # (stress, anxiety, depression, neutral)
kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
labels = kmeans.fit_predict(emb)

df["cluster"] = labels

# ---------------------------------------------------
# 5️. CLUSTER NAME MAPPING (auto-detect using keywords)
# ---------------------------------------------------
cluster_names = {}

keywords = {
    "stress": ["pressure", "tension", "overload", "burnout", "exhausted"],
    "anxiety": ["scared", "fear", "worry", "panic", "anxious"],
    "depression": ["sad", "alone", "hopeless", "empty", "cry"],
    "neutral": []
}

for c in range(k):
    sample_texts = " ".join(df[df["cluster"] == c]["text"].head(30)).lower()
    assigned = "neutral"
    for label, keys in keywords.items():
        if any(word in sample_texts for word in keys):
            assigned = label
            break
    cluster_names[c] = assigned

df["prediction"] = df["cluster"].map(cluster_names)

# ---------------------------------------------------
# 6️. SAVE RESULTS
# ---------------------------------------------------
df.to_csv("/content/drive/MyDrive/Colab Notebooks/dataset.csv", index=False)
print("\n📁 Saved → mental_health_predictions.csv")

df[["text","prediction"]].head()

"""# **AI-Driven Mental Health Prediction Model**

This code builds a complete machine-learning pipeline to classify mental-health related tweets using multiple models and compares which one performs best. It loads and cleans the dataset, merges text from different columns, and creates labels either from the dataset or through keyword heuristics. The text is then converted into numerical features using both TF-IDF and transformer-based embeddings. Several models like Logistic Regression, SVM, and Random Forest are trained and evaluated on accuracy, precision, recall, and F1-score. A bar graph is generated to show which model performs the best, and finally, the chosen model predicts labels for the entire dataset and saves the results.

- Smart Data Cleaning: Removes missing values, duplicates, and merges tweet-related text into a single column.

- Auto-Labeling: If no label exists, it assigns labels using mental-health keywords.

- Multiple Text Representations: Uses TF-IDF features and transformer embeddings (all-MiniLM-L6-v2).

- Model Training: Trains four models — Logistic Regression, LinearSVC, Random Forest — on different vector types.

- Fair Evaluation: Compares all models using accuracy, precision, recall, and F1-score.

- Graph Visualization: Plots a bar chart to show which model performs best.

- Best Model Selection: Automatically picks the top-performing model based on your chosen metric.

- Final Output: Adds predictions to the dataset and saves the updated CSV file.
"""

!pip install -q sentence-transformers scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sentence_transformers import SentenceTransformer
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

# -------------------------
# Config
# -------------------------
DATA_PATH = "/content/drive/MyDrive/Colab Notebooks/dataset.csv"   # path to your uploaded CSV
TEXT_COL = "tweet"    # primary text column (will autodetect if missing)
RANDOM_STATE = 42
TEST_SIZE = 0.2
METRIC = "f1"   # change to 'accuracy' or 'precision' or 'recall' if desired
PLOT_PATH = "model_comparison.png"

# -------------------------
# 1) Load data
# -------------------------
assert os.path.exists(DATA_PATH), f"Dataset not found at {DATA_PATH}"
df = pd.read_csv(DATA_PATH)
df = df.fillna("")
df = df.drop_duplicates()
print("Loaded:", df.shape)

# autodetect text column if TEXT_COL not present
if TEXT_COL not in df.columns:
    candidates = ["text","post","content"]
    for c in candidates:
        if c in df.columns:
            TEXT_COL = c
            break
print("Using text column:", TEXT_COL)

# create a unified text column (safe)
text_cols = [TEXT_COL]
for c in ["username","name","place"]:
    if c in df.columns:
        text_cols.append(c)
df["text"] = df[text_cols].astype(str).agg(" ".join, axis=1).str.strip()

# -------------------------
# 2) Create or use label
# -------------------------
label_col = None
for c in df.columns:
    if c.lower() in ["label","target","sentiment"]:
        label_col = c
        break

if label_col is None:
    print("No label column found — creating heuristic labels (keyword-based).")
    keywords = ["sad","depress","anxious","anxiety","alone","hopeless","suicide","panic","cry","lonely","stress","stressed","worry"]
    def heuristic_label(txt):
        t = str(txt).lower()
        return int(any(k in t for k in keywords))
    df["label"] = df["text"].apply(heuristic_label)
    label_col = "label"
else:
    print("Using existing label column:", label_col)
    # try to coerce to binary numeric
    if df[label_col].dtype == object:
        df[label_col] = df[label_col].astype(str).str.lower().map(
            lambda x: 1 if any(k in x for k in ["depress","yes","positive","1","sensitive"]) else 0
        ).fillna(0).astype(int)

# drop rows with empty text
df = df[df["text"].str.strip() != ""].reset_index(drop=True)
print("After cleaning:", df.shape)
y = df[label_col].astype(int).values
X_text = df["text"].values

# -------------------------
# 3) Train-test split (stratified)
# -------------------------
X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text, y, test_size=TEST_SIZE, stratify=y, random_state=RANDOM_STATE
)
print("Train/Test sizes:", X_train_text.shape[0], X_test_text.shape[0])

# -------------------------
# 4) Prepare vectorizers & models
# -------------------------
# TF-IDF vectorizer (fast)
tfidf = TfidfVectorizer(max_features=7000, ngram_range=(1,2), stop_words="english")

# sentence-transformer embeddings (all-MiniLM)
embed_model = SentenceTransformer("all-MiniLM-L6-v2")  # small and fast

# Initialize classifiers
models = {
    "TFIDF + LogisticRegression": LogisticRegression(max_iter=1000, class_weight="balanced"),
    "TFIDF + LinearSVC": LinearSVC(max_iter=5000, class_weight="balanced"),
    "Embeddings + LogisticRegression": LogisticRegression(max_iter=1000, class_weight="balanced"),
    "Embeddings + RandomForest": RandomForestClassifier(n_estimators=200, n_jobs=-1, class_weight="balanced")
}

# -------------------------
# 5) Train TF-IDF based models
# -------------------------
print("Fitting TF-IDF...")
X_train_tfidf = tfidf.fit_transform(X_train_text)
X_test_tfidf = tfidf.transform(X_test_text)

print("Training TF-IDF models...")
models["TFIDF + LogisticRegression"].fit(X_train_tfidf, y_train)
models["TFIDF + LinearSVC"].fit(X_train_tfidf, y_train)

# -------------------------
# 6) Prepare embeddings (fast, batched)
# -------------------------
print("Computing embeddings (this may take a moment)...")
train_emb = embed_model.encode(list(X_train_text), batch_size=64, show_progress_bar=True)
test_emb = embed_model.encode(list(X_test_text), batch_size=64, show_progress_bar=True)

# train embedding-based models
models["Embeddings + LogisticRegression"].fit(train_emb, y_train)
models["Embeddings + RandomForest"].fit(train_emb, y_train)

# -------------------------
# 7) Evaluate all models and collect metrics
# -------------------------
results = []
for name, m in models.items():
    if name.startswith("TFIDF"):
        X_test_in = X_test_tfidf
    else:
        X_test_in = test_emb
    preds = m.predict(X_test_in)
    acc = accuracy_score(y_test, preds)
    prec = precision_score(y_test, preds, zero_division=0)
    rec = recall_score(y_test, preds, zero_division=0)
    f1 = f1_score(y_test, preds, zero_division=0)
    results.append({
        "model": name,
        "accuracy": acc,
        "precision": prec,
        "recall": rec,
        "f1": f1
    })
    print(f"\n{name} -> acc:{acc:.4f} prec:{prec:.4f} rec:{rec:.4f} f1:{f1:.4f}")

res_df = pd.DataFrame(results).set_index("model")
print("\nSummary:\n", res_df)

# -------------------------
# 8) Plot comparison (default: METRIC)
# -------------------------
metric = METRIC.lower()
if metric not in ["accuracy","precision","recall","f1"]:
    metric = "f1"

plt.figure(figsize=(10,6))
ax = sns.barplot(x=res_df.index, y=res_df[metric].values)
plt.title(f"Model comparison — {metric.upper()} score")
plt.ylabel(metric.upper())
plt.ylim(0,1)
plt.xticks(rotation=25)
for i, v in enumerate(res_df[metric].values):
    ax.text(i, v + 0.01, f"{v:.3f}", ha="center", fontweight="bold")
plt.tight_layout()
plt.savefig(PLOT_PATH, dpi=200)
print(f"\nPlot saved to {PLOT_PATH}")
plt.show()

# -------------------------
# 9) Save predictions and results
# -------------------------
# Add predictions from best model to dataframe (by chosen metric)
best_model_name = res_df[metric].idxmax()
print("Best model by", metric, ":", best_model_name)
best_model = models[best_model_name]
if best_model_name.startswith("TFIDF"):
    preds_all = best_model.predict(tfidf.transform(df["text"].values))
else:
    preds_all = best_model.predict(embed_model.encode(df["text"].tolist(), batch_size=64, show_progress_bar=False))
df["predicted_label"] = preds_all
df["predicted_label_prob"] = None  # for simple models we skip probabilities here

OUT_CSV = "/content/drive/MyDrive/Colab Notebooks/dataset.csv"
df.to_csv(OUT_CSV, index=False)
print("Saved predictions to", OUT_CSV)

"""# **ML Model Comparison With Line Graph**

This code performs a complete comparison of multiple machine-learning models to identify which algorithm predicts mental-health related text most accurately. It loads and cleans the dataset, automatically creates labels using mental-health keywords if none exist, and splits the text into training and testing sets. Two types of features—TF-IDF vectors and transformer embeddings—are generated, and four different classifiers are trained. Each model’s accuracy, precision, recall, and F1-score are calculated, and a line graph is drawn to visually compare their performance. Finally, the model with the highest F1-score is selected automatically as the best algorithm.

- Data Preprocessing: Loads CSV, removes duplicates, prepares a clean text column.

- Auto Labeling: Creates labels using mental-health keywords when missing.

- Feature Engineering: Converts text into TF-IDF and MiniLM transformer embeddings.

- Model Training: Logistic Regression, Linear SVC, and Random Forest models are trained with both vector types.

- Evaluation Metrics: Computes accuracy, precision, recall, and F1-score for every model.

- Line Graph: Plots all model metrics for easy visual comparison.

- Best Model Selection: Automatically picks the algorithm with the highest F1-score.
"""

# ML Comparison With Line Graph + Best Algorithm Selection
# --------------------------------------------------------

!pip install -q sentence-transformers scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sentence_transformers import SentenceTransformer
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

DATA_PATH = "/content/drive/MyDrive/Colab Notebooks/dataset.csv"
TEXT_COL = "tweet"
METRIC = "f1"
TEST_SIZE = 0.2
RANDOM_STATE = 42

# --------------------------------------------------------
# 1. Load Data
# --------------------------------------------------------
df = pd.read_csv(DATA_PATH).fillna("").drop_duplicates()

if TEXT_COL not in df.columns:
    for c in ["text","content","post"]:
        if c in df.columns:
            TEXT_COL = c
            break

df["text"] = df[TEXT_COL].astype(str)

# Create label if not present
if "label" not in df.columns:
    keywords = ["sad","depress","anxiety","panic","stress","cry","hopeless","suicide"]
    df["label"] = df["text"].str.lower().apply(lambda x: int(any(k in x for k in keywords)))

df = df[df["text"].str.strip() != ""].reset_index(drop=True)
y = df["label"].astype(int).values
X = df["text"].values

# --------------------------------------------------------
# 2. Train/Test Split
# --------------------------------------------------------
X_train_text, X_test_text, y_train, y_test = train_test_split(
    X, y, test_size=TEST_SIZE, stratify=y, random_state=RANDOM_STATE
)

# --------------------------------------------------------
# 3. Vectorizers
# --------------------------------------------------------
tfidf = TfidfVectorizer(max_features=7000, ngram_range=(1,2), stop_words="english")
X_train_tfidf = tfidf.fit_transform(X_train_text)
X_test_tfidf = tfidf.transform(X_test_text)

embedder = SentenceTransformer("all-MiniLM-L6-v2")
train_emb = embedder.encode(list(X_train_text), batch_size=64, show_progress_bar=False)
test_emb = embedder.encode(list(X_test_text), batch_size=64, show_progress_bar=False)

# --------------------------------------------------------
# 4. ML Models
# --------------------------------------------------------
models = {
    "TFIDF + LogisticRegression": LogisticRegression(max_iter=1000, class_weight="balanced"),
    "TFIDF + LinearSVC": LinearSVC(max_iter=5000, class_weight="balanced"),
    "Embeddings + LogisticRegression": LogisticRegression(max_iter=1000, class_weight="balanced"),
    "Embeddings + RandomForest": RandomForestClassifier(n_estimators=200, n_jobs=-1, class_weight="balanced")
}

# Training
models["TFIDF + LogisticRegression"].fit(X_train_tfidf, y_train)
models["TFIDF + LinearSVC"].fit(X_train_tfidf, y_train)
models["Embeddings + LogisticRegression"].fit(train_emb, y_train)
models["Embeddings + RandomForest"].fit(train_emb, y_train)

# --------------------------------------------------------
# 5. Evaluate All Models
# --------------------------------------------------------
results = []

for name, model in models.items():
    data_test = X_test_tfidf if "TFIDF" in name else test_emb
    preds = model.predict(data_test)

    acc = accuracy_score(y_test, preds)
    prec = precision_score(y_test, preds, zero_division=0)
    rec = recall_score(y_test, preds, zero_division=0)
    f1 = f1_score(y_test, preds, zero_division=0)

    results.append([name, acc, prec, rec, f1])

results_df = pd.DataFrame(results, columns=["Model","Accuracy","Precision","Recall","F1"]).set_index("Model")
print(results_df)

# --------------------------------------------------------
# 6. Line Graph
# --------------------------------------------------------
plt.figure(figsize=(10,6))
for metric in ["Accuracy","Precision","Recall","F1"]:
    plt.plot(results_df.index, results_df[metric], marker="o", linewidth=2, label=metric)

plt.title("Model Performance Comparison (Line Graph)")
plt.xticks(rotation=25)
plt.ylabel("Score")
plt.ylim(0,1)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# --------------------------------------------------------
# 7. Best Model (Automatically)
# --------------------------------------------------------
best_model_name = results_df[METRIC.capitalize()].idxmax()
best_score = results_df.loc[best_model_name, METRIC.capitalize()]
print(f"\n🔥 BEST MODEL: {best_model_name}  (F1 = {best_score:.4f})")

"""# **Future Work: Advanced Mental-Health Trend & Recommendation Pipeline**

This advanced script builds a complete, high-speed AI pipeline that loads and cleans mental-health text data, generates sentence-level embeddings using a transformer model, reduces their dimensions for speed, trains multiple machine-learning models, compares their performance, analyzes monthly mental-health trends, and finally creates a smart recommendation system to suggest similar posts. It uses caching, PCA, LightGBM (if available), TF-IDF, logistic regression, and nearest-neighbor search to ensure the pipeline is both fast and scalable.


- Optimized Data Loading: Cleans text, handles missing values, and auto-generates labels if not provided.


- Transformer Embeddings: Converts text into numerical vectors using SBERT with caching for fast re-runs.


- Dimensionality Reduction: Applies PCA to speed up model training and reduce memory usage.


- Multi-Model Training: Trains TF-IDF + Logistic, Embeddings + Logistic, and Embeddings + LightGBM (or Random Forest).


- Performance Ranking: Evaluates all models using accuracy, precision, recall, and F1 to select the best one.


- Trend Analysis: Generates smooth 3-month rolling trend graphs based on predicted labels over time.


- Recommendation Engine: Uses Nearest Neighbors on reduced embeddings to find similar mental-health posts.


- Artifacts Saved: Stores models, embeddings, plots, and metrics for future deployment and analysis.


"""

import os
import re
import time
import joblib
import numpy as np
import pandas as pd
from pathlib import Path
from datetime import datetime
import matplotlib.pyplot as plt

# sklearn / ml
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.pipeline import make_pipeline

# try fast booster (LightGBM) else fallback
try:
    import lightgbm as lgb
    LGB_AVAILABLE = True
except Exception:
    LGB_AVAILABLE = False

# sentence-transformers (fast, GPU-supported encoding)
from sentence_transformers import SentenceTransformer

# -------------------------
# CONFIG
# -------------------------
DATA_PATH = "/content/drive/MyDrive/Colab Notebooks/dataset.csv"   # <-- change to your CSV
TEXT_COL = "text"   # primary textual column in your CSV (or 'tweet')
LABEL_COL = "label" # should be binary or categorical (0/1 or strings)
DATE_COL = "date"   # date/time column name
EMB_MODEL_NAME = "all-MiniLM-L6-v2"
EMB_CACHE = "cached_embeddings.npy"
PCA_CACHE = "cached_pca.joblib"
EMB_DIM_REDUCED = 128    # PCA dims (balance speed & quality)
TEST_SIZE = 0.20
RANDOM_STATE = 42
RESULT_DIR = "results_fast"
os.makedirs(RESULT_DIR, exist_ok=True)

# -------------------------
# 0. Utility: text cleaning (vectorized, fast)
# -------------------------
def clean_text_series(s: pd.Series) -> pd.Series:
    # lower, remove urls, non-alpha & extra spaces
    s = s.astype(str).str.lower()
    s = s.str.replace(r"http\S+", "", regex=True)
    s = s.str.replace(r"[^a-z\s]", " ", regex=True)
    s = s.str.replace(r"\s+", " ", regex=True).str.strip()
    return s

# -------------------------
# 1. Load data
# -------------------------
print("Loading dataset...", end=" ")
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset.csv")
assert TEXT_COL in df.columns, f"{TEXT_COL} not found in CSV columns: {df.columns.tolist()}"
print("done. Rows:", len(df))

# ensure date column parsed (if present)
if DATE_COL in df.columns:
    df[DATE_COL] = pd.to_datetime(df[DATE_COL], errors="coerce")
else:
    df[DATE_COL] = pd.NaT

# basic cleaning: drop null text rows
df = df[df[TEXT_COL].astype(str).str.strip() != ""].reset_index(drop=True)

# if label not present, create heuristic binary label using keywords (fast)
if LABEL_COL not in df.columns:
    print("No label column found — creating heuristic binary label using keywords.")
    kws = ["sad","depress","anxiety","panic","stress","suicide","hopeless","lonely","cry"]
    df[LABEL_COL] = df[TEXT_COL].astype(str).str.lower().apply(lambda t: int(any(k in t for k in kws)))
else:
    # ensure numeric labels for classification
    if df[LABEL_COL].dtype == object:
        # simple map for common patterns; else try convert to int
        df[LABEL_COL] = df[LABEL_COL].astype(str).str.lower().map(lambda x: 1 if any(k in x for k in ["1","yes","depress","positive","true"]) else 0).astype(int)

print("After cleaning:", df.shape)

# -------------------------
# 2. Fast Text Preprocessing
# -------------------------
print("Cleaning text (vectorized)...", end=" ")
df["clean_text"] = clean_text_series(df[TEXT_COL])
print("done.")

# -------------------------
# 3. Embeddings (cached)
# -------------------------
embedder = SentenceTransformer(EMB_MODEL_NAME)
if Path(EMB_CACHE).exists():
    print(f"Loading cached embeddings from {EMB_CACHE} ...", end=" ")
    embeddings = np.load(EMB_CACHE)
    print("done.")
else:
    print("Encoding texts to embeddings (batched)...")
    t0 = time.time()
    embeddings = embedder.encode(df["clean_text"].tolist(), batch_size=64, show_progress_bar=True, convert_to_numpy=True)
    np.save(EMB_CACHE, embeddings)
    print(f"Embeddings saved to {EMB_CACHE} — time {time.time()-t0:.1f}s")

# -------------------------
# 4. Dimensionality Reduction (PCA) for speed + memory
# -------------------------
if Path(PCA_CACHE).exists():
    pca = joblib.load(PCA_CACHE)
    emb_reduced = pca.transform(embeddings)
else:
    pca = PCA(n_components=min(EMB_DIM_REDUCED, embeddings.shape[1]), random_state=RANDOM_STATE)
    emb_reduced = pca.fit_transform(embeddings)
    joblib.dump(pca, PCA_CACHE)
print("Embeddings reduced -> shape:", emb_reduced.shape)

# -------------------------
# 5. Train-test split (stratify if possible)
# -------------------------
y = df[LABEL_COL].astype(int).values
X_train_emb, X_test_emb, y_train, y_test, idx_train, idx_test = train_test_split(
    emb_reduced, y, df.index.values, test_size=TEST_SIZE, stratify=y if len(np.unique(y))>1 else None, random_state=RANDOM_STATE
)
# also prepare TF-IDF baseline (fast)
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2), stop_words="english")
X_tfidf = tfidf.fit_transform(df["clean_text"])
X_train_tfidf = X_tfidf[idx_train]
X_test_tfidf = X_tfidf[idx_test]

print("Train/Test sizes:", X_train_emb.shape[0], X_test_emb.shape[0])

# -------------------------
# 6. FAST MODELS: choose LightGBM if available else LogisticRegression with saga solver
# -------------------------
models = {}
results = []

# Helper: evaluate
def evaluate(name, preds, y_true):
    return {
        "model": name,
        "accuracy": accuracy_score(y_true, preds),
        "precision": precision_score(y_true, preds, zero_division=0),
        "recall": recall_score(y_true, preds, zero_division=0),
        "f1": f1_score(y_true, preds, zero_division=0)
    }

# TF-IDF + Logistic (fast)
print("Training TF-IDF + LogisticRegression (fast)...", end=" ")
clf_tfidf = LogisticRegression(max_iter=200, solver="saga", n_jobs=-1, class_weight="balanced", random_state=RANDOM_STATE)
clf_tfidf.fit(X_train_tfidf, y_train)
preds = clf_tfidf.predict(X_test_tfidf)
results.append(evaluate("TFIDF+Logistic", preds, y_test))
print("done.")

# Embeddings + Logistic
print("Training Embeddings + LogisticRegression...", end=" ")
clf_emb_log = LogisticRegression(max_iter=200, solver="saga", n_jobs=-1, class_weight="balanced", random_state=RANDOM_STATE)
clf_emb_log.fit(X_train_emb, y_train)
preds = clf_emb_log.predict(X_test_emb)
results.append(evaluate("Emb+Logistic", preds, y_test))
print("done.")

# Embeddings + LightGBM (fast) or RandomForest fallback
if LGB_AVAILABLE:
    print("Training Embeddings + LightGBM (fast)...", end=" ")
    lgb_train = lgb.Dataset(X_train_emb, label=y_train)
    params = {"objective":"binary", "metric":"binary_logloss", "verbosity":-1, "boosting_type":"gbdt", "num_threads": 4}
    lgbm = lgb.train(params, lgb_train, num_boost_round=100)
    preds = (lgbm.predict(X_test_emb) > 0.5).astype(int)
    results.append(evaluate("Emb+LightGBM", preds, y_test))
    print("done.")
else:
    print("LightGBM not available — using Embeddings + RandomForest (may be slower).", end=" ")
    from sklearn.ensemble import RandomForestClassifier
    rf = RandomForestClassifier(n_estimators=150, n_jobs=-1, class_weight="balanced", random_state=RANDOM_STATE)
    rf.fit(X_train_emb, y_train)
    preds = rf.predict(X_test_emb)
    results.append(evaluate("Emb+RandomForest", preds, y_test))
    print("done.")

# collect results dataframe
res_df = pd.DataFrame(results).set_index("model")
print("\nModel comparison:\n", res_df)

# -------------------------
# 7. Plot metrics (line graph) - saves to results folder
# -------------------------
metric_order = ["accuracy","precision","recall","f1"]
plt.figure(figsize=(10,5))
for m in metric_order:
    plt.plot(res_df.index, res_df[m].values, marker="o", label=m.upper())
plt.title("Model Comparison — Metrics")
plt.ylim(0,1)
plt.grid(True); plt.legend(); plt.xticks(rotation=20)
plt.tight_layout()
plt.savefig(os.path.join(RESULT_DIR, "model_comparison_line.png"), dpi=200)
plt.close()
print("Saved model comparison plot ->", os.path.join(RESULT_DIR, "model_comparison_line.png"))

# -------------------------
# 8. Trend over time (monthly + rolling avg)
# -------------------------
if not df[DATE_COL].isna().all():
    # map predicted labels for full dataset using best model by F1
    best_model_name = res_df["f1"].idxmax()
    print("Best model by F1:", best_model_name)
    if best_model_name == "TFIDF+Logistic":
        full_preds = clf_tfidf.predict(X_tfidf)
    elif best_model_name == "Emb+Logistic":
        full_preds = clf_emb_log.predict(pca.transform(embeddings))
    elif best_model_name == "Emb+LightGBM" and LGB_AVAILABLE:
        full_preds = (lgbm.predict(pca.transform(embeddings))>0.5).astype(int)
    else:
        # if random forest fallback used
        full_preds = rf.predict(pca.transform(embeddings)) if 'rf' in locals() else clf_emb_log.predict(pca.transform(embeddings))

    df["predicted_label"] = full_preds

    # ensure month period
    df["month"] = df[DATE_COL].dt.to_period("M")
    trend = df.groupby(["month", "predicted_label"]).size().reset_index(name="count")
    # pivot for plotting
    trend_pivot = trend.pivot(index="month", columns="predicted_label", values="count").fillna(0)
    # rolling mean (3 months) for smooth trend
    trend_smoothed = trend_pivot.rolling(window=3, min_periods=1).mean()

    plt.figure(figsize=(12,5))
    for col in trend_smoothed.columns:
        plt.plot(trend_smoothed.index.astype(str), trend_smoothed[col], marker="o", label=f"label_{col}")
    plt.xticks(rotation=45)
    plt.title("Monthly Trends (3-month rolling avg)")
    plt.ylabel("Post counts (smoothed)")
    plt.legend()
    plt.tight_layout()
    trend_path = os.path.join(RESULT_DIR, "trend_monthly_smoothed.png")
    plt.savefig(trend_path, dpi=200)
    plt.close()
    print("Saved trend graph ->", trend_path)
else:
    print("No valid date column available — skipping trend analysis.")

# -------------------------
# 9. Smart content-based Recommendations (NearestNeighbors on reduced embeddings)
# -------------------------
# build nearest neighbors on reduced embeddings (fast)
nn = NearestNeighbors(n_neighbors=6, metric="cosine", n_jobs=-1).fit(emb_reduced)

def recommend_similar(text: str, top_k: int = 5):
    """Return top_k similar posts from dataset for given input text"""
    text_clean = clean_text_series(pd.Series([text]))[0]
    emb = embedder.encode([text_clean], convert_to_numpy=True)
    emb_r = pca.transform(emb)
    dists, idxs = nn.kneighbors(emb_r, n_neighbors=top_k+1)  # +1 to skip itself if in DS
    idxs = idxs[0]
    dists = dists[0]
    # remove self if present (distance==0)
    results = []
    for dist, i in zip(dists, idxs):
        results.append({"index": int(i), "text": df.iloc[i][TEXT_COL], "pred_label": int(df.iloc[i][LABEL_COL]), "distance": float(dist)})
    return results[1:top_k+1] if len(results)>1 else results

# quick test
sample_q = "I feel lonely and can't sleep for nights."
print("Sample recommendations (fast):")
recs = recommend_similar(sample_q, top_k=5)
for r in recs:
    print(f"- idx:{r['index']} | dist:{r['distance']:.3f} | label:{r['pred_label']} | text: {r['text'][:120]}")

# -------------------------
# 10. Save artifacts & short report
# -------------------------
res_df.to_csv(os.path.join(RESULT_DIR, "model_metrics.csv"))
np.save(os.path.join(RESULT_DIR, "emb_reduced.npy"), emb_reduced)
joblib.dump(clf_tfidf, os.path.join(RESULT_DIR, "clf_tfidf.joblib"))
joblib.dump(clf_emb_log, os.path.join(RESULT_DIR, "clf_emb_log.joblib"))
if LGB_AVAILABLE:
    lgbm.save_model(os.path.join(RESULT_DIR, "lgbm_model.txt"))
else:
    if 'rf' in locals():
        joblib.dump(rf, os.path.join(RESULT_DIR, "rf_model.joblib"))

print("Artifacts saved to", RESULT_DIR)
print("DONE — Fast pipeline executed.")

# ================================================
# NOTES & TIPS:
# - Re-run is fast because embeddings are cached (EMB_CACHE).
# - To further speed up: reduce PCA dims, run on GPU-enabled Colab for sentence-transformers.
# - To enable multilingual functionality: use multilingual SBERT model like 'paraphrase-multilingual-MiniLM-L12-v2'.
# - For privacy-aware POC: compute embeddings on-device and only send reduced embeddings (or use federated setup).
# ================================================